const PLUS: u8 = 0x2B;
const MINUS: u8 = 0x2D;
const MULTIPLY: u8 = 0x2A;
const DIVISION: u8 = 0x2F;

#[cfg(windows)]
const NEW_LINE: &[u8] = b"\r\n";

#[cfg(not(windows))]
const NEW_LINE: &[u8] = b"\n";

#[derive(Debug)]
pub enum Token {
    Number(i32),
    Plus,
    Minus,
    Multiply,
    Division,
}

fn flush_acc(token: &mut Vec<Token>, acc: &mut i32, has_number: &mut bool) {
    if *has_number == true {
        token.push(Token::Number(*acc));
        *acc = 0;
        *has_number = false;
    }
}

pub fn lexer(input: &str) -> Vec<Token> {
    let mut token: Vec<Token> = Vec::new(); // final token output

    let mut acc: i32 = 0;
    let mut has_number: bool = false;
        
    for b in input.bytes() {  // iterate over input bytes
        match b {
            b'0'..=b'9' => { // if b is a digit from 0 to 9, append it to acc and set has_number
                acc = acc * 10 + (b - b'0') as i32;
                has_number = true;
            },

            _ if NEW_LINE.contains(&b) => { // on newline, flush the accumulator to push the final value to tokens
                flush_acc(&mut token, &mut acc, &mut has_number);
            },

            // operators
            PLUS => {
                flush_acc(&mut token, &mut acc, &mut has_number);
                token.push(Token::Plus);
            },

            MINUS => {
                flush_acc(&mut token, &mut acc, &mut has_number);
                token.push(Token::Minus);
            },

            MULTIPLY => {
                flush_acc(&mut token, &mut acc, &mut has_number);
                token.push(Token::Multiply);
            },

            DIVISION => {
                flush_acc(&mut token, &mut acc, &mut has_number);
                token.push(Token::Division);
            }, 

             _ => {},// ignore any other characters
        }
    }

    return token; // return tokens generated by the lexer
}
